# Generated by Django 5.1.2 on 2025-02-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile",
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
