# Generated by Django 5.1.2 on 2025-03-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_post_edited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
